export type GearTier = 'starter' | 'growth' | 'pro'

export type GearCategory =
  | 'camera'
  | 'lens'
  | 'lavalier-mic'
  | 'usb-mic'
  | 'dynamic-mic'
  | 'shotgun-mic'
  | 'lighting'
  | 'teleprompter'
  | 'tripod'
  | 'gimbal'
  | 'drone'
  | 'storage'
  | 'streamdeck'
  | 'accessory'
  | 'software-editing'
  | 'software-ai'
  | 'software-growth'
  | 'software-leadgen'
  | 'software-repurpose'

export interface GearProduct {
  slug: string
  name: string
  category: GearCategory
  tier: GearTier
  priceLow: number
  priceHigh: number
  brand: string
  notes: string
  why: string[]
  useCase: string
  amazonUrl?: string
  imagePath: string
  aaronUses: boolean
}

export const gear: GearProduct[] = [
  // ===== STARTER TIER =====
  {
    slug: 'smartphone-camera',
    name: 'Your Smartphone (iPhone 14+ or Samsung S23+)',
    category: 'camera',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 0,
    brand: 'Apple/Samsung',
    notes: 'Free. You already own it.',
    why: [
      'Shoot in 4K at 30fps',
      'Use back camera, never the selfie cam',
      'Modern phones rival entry-level mirrorless cameras',
      'Zero new equipment to learn',
    ],
    useCase: 'Anyone starting out. Period.',
    imagePath: '/photos/gear/smartphone-camera.jpg',
    aaronUses: false,
  },
  {
    slug: 'ubeesize-67-tripod',
    name: 'UBeesize 67" Phone Tripod',
    category: 'tripod',
    tier: 'starter',
    priceLow: 25,
    priceHigh: 35,
    brand: 'UBeesize',
    notes: 'Phone + camera compatible. Remote shutter included.',
    why: [
      'Works with both phones and cameras',
      '67 inches tall (no awkward filming angles)',
      'Bluetooth remote in the box',
      'Lightweight, travels well',
    ],
    useCase: 'Talking head, property tours, any locked-off shot.',
    imagePath: '/photos/gear/ubeesize-67-tripod.jpg',
    aaronUses: false,
  },
  {
    slug: 'hollyland-lark-m2',
    name: 'Hollyland Lark M2',
    category: 'lavalier-mic',
    tier: 'starter',
    priceLow: 50,
    priceHigh: 80,
    brand: 'Hollyland',
    notes: 'Best budget wireless mic in 2026',
    why: [
      'Wireless with 1000ft range',
      '48kHz/24bit audio quality',
      'Fast pairing, idiot-proof setup',
      '8 hour battery life',
    ],
    useCase: "Anyone filming outside, in cars, or moving around. Don't bother with a wired lav if you're filming property tours.",
    imagePath: '/photos/gear/hollyland-lark-m2.jpg',
    aaronUses: false,
  },
  {
    slug: 'dji-mic-mini',
    name: 'DJI Mic Mini',
    category: 'lavalier-mic',
    tier: 'starter',
    priceLow: 70,
    priceHigh: 90,
    brand: 'DJI',
    notes: 'Ultralight alternative to Hollyland Lark M2',
    why: [
      'Only 10g per transmitter',
      '400m range',
      '48hr battery with charging case',
      'Disappears under clothing',
    ],
    useCase: 'On-camera personalities who want the mic invisible. Property tour creators who walk a lot.',
    imagePath: '/photos/gear/dji-mic-mini.jpg',
    aaronUses: true,
  },
  {
    slug: 'maono-pd300x',
    name: 'Maono PD300X',
    category: 'usb-mic',
    tier: 'starter',
    priceLow: 50,
    priceHigh: 70,
    brand: 'Maono',
    notes: 'USB + XLR dual output. Grow into it.',
    why: [
      'Dual USB and XLR connections',
      'Clear vocal profile out of the box',
      'No interface needed for USB mode',
      "Upgrade path when you're ready for an audio interface",
    ],
    useCase: 'Desk-based talking head. Podcasters. Anyone who films in one fixed location.',
    imagePath: '/photos/gear/maono-pd300x.jpg',
    aaronUses: false,
  },
  {
    slug: 'neewer-18-ring-light',
    name: 'Neewer 18" Ring Light',
    category: 'lighting',
    tier: 'starter',
    priceLow: 40,
    priceHigh: 60,
    brand: 'Neewer',
    notes: 'Adjustable color temp. Phone mount built in.',
    why: [
      'Adjustable color temperature (warm to cool)',
      'Phone mount in the center',
      'Even, flattering light on the face',
      'Compact, easy storage',
    ],
    useCase: 'Indoor talking head. Anyone filming at a desk or against a wall.',
    imagePath: '/photos/gear/neewer-18-ring-light.jpg',
    aaronUses: false,
  },
  {
    slug: 'elgato-key-light-mini',
    name: 'Elgato Key Light Mini',
    category: 'lighting',
    tier: 'starter',
    priceLow: 80,
    priceHigh: 80,
    brand: 'Elgato',
    notes: 'Portable, app-controlled, excellent for desk setups',
    why: [
      'App control (no fumbling with physical knobs on camera)',
      'Battery powered (works anywhere)',
      'High CRI for accurate skin tones',
      'Stackable for two-light setups',
    ],
    useCase: 'Desk creators who want pro lighting without a stand and softbox.',
    imagePath: '/photos/gear/elgato-key-light-mini.jpg',
    aaronUses: true,
  },
  {
    slug: 'promptsmart-pro',
    name: 'PromptSmart Pro (App)',
    category: 'teleprompter',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 20,
    brand: 'PromptSmart',
    notes: 'Voice-activated scrolling. Works on any tablet.',
    why: [
      'Scrolls to your voice (no foot pedal)',
      'Recognizes when you skip or repeat',
      'Works on phones and tablets',
      'One-time purchase, no subscription',
    ],
    useCase: "Anyone who needs script support but doesn't want to look like they're reading.",
    imagePath: '/photos/gear/promptsmart-pro.jpg',
    aaronUses: false,
  },

  // ===== GROWTH TIER =====
  {
    slug: 'sony-zv-e10-ii',
    name: 'Sony ZV-E10 II',
    category: 'camera',
    tier: 'growth',
    priceLow: 900,
    priceHigh: 1100,
    brand: 'Sony',
    notes: 'Best vlogging camera in 2026',
    why: [
      '4K with no crop',
      'Excellent built-in directional mic',
      'Flip-out screen for self-monitoring',
      'Interchangeable lens system (room to grow)',
      'Compact and lightweight',
    ],
    useCase: "Anyone who's outgrown their phone and is ready to invest in real glass.",
    imagePath: '/photos/gear/sony-zv-e10-ii.jpg',
    aaronUses: true,
  },
  {
    slug: 'sony-zv-1-ii',
    name: 'Sony ZV-1 II',
    category: 'camera',
    tier: 'growth',
    priceLow: 700,
    priceHigh: 800,
    brand: 'Sony',
    notes: 'Compact alternative to ZV-E10 II. Fixed lens.',
    why: [
      'Compact one-piece design',
      'Excellent autofocus tracking',
      'Wide-angle lens built in (no lens swap needed)',
      'Pocket-friendly for travel',
    ],
    useCase: "Creators who want one device and don't want to think about lens decisions.",
    imagePath: '/photos/gear/sony-zv-1-ii.jpg',
    aaronUses: true,
  },
  {
    slug: 'sony-16-50mm-kit-lens',
    name: 'Sony 16-50mm f/3.5-5.6',
    category: 'lens',
    tier: 'growth',
    priceLow: 300,
    priceHigh: 350,
    brand: 'Sony',
    notes: 'Kit lens for ZV-E10 II',
    why: [
      'Versatile zoom range (wide to short telephoto)',
      'Lightweight',
      'Pairs perfectly with ZV-E10 II body',
      'Covers talking head AND property tours in one lens',
    ],
    useCase: 'Default lens for the ZV-E10 II until you know what specialty glass you actually need.',
    imagePath: '/photos/gear/sony-16-50mm-kit-lens.jpg',
    aaronUses: true,
  },
  {
    slug: 'rode-wireless-go-ii',
    name: 'Rode Wireless Go II',
    category: 'lavalier-mic',
    tier: 'growth',
    priceLow: 250,
    priceHigh: 300,
    brand: 'Rode',
    notes: 'Dual-channel wireless. 200m range. On-board recording backup.',
    why: [
      'Two transmitters in one kit (interview-ready)',
      '200m range',
      'Records to onboard memory as a backup',
      'Industry standard for content creators',
    ],
    useCase: "Two-person interviews, property walkthroughs with co-host, anyone who's gone wireless and never going back.",
    imagePath: '/photos/gear/rode-wireless-go-ii.jpg',
    aaronUses: false,
  },
  {
    slug: 'rode-videomic-pro-plus',
    name: 'Rode VideoMic Pro+',
    category: 'shotgun-mic',
    tier: 'growth',
    priceLow: 250,
    priceHigh: 250,
    brand: 'Rode',
    notes: 'On-camera shotgun. Great for mobile/outdoor shooting.',
    why: [
      'Mounts directly to camera hot shoe',
      'Great for outdoor and mobile shooting',
      'Auto power on/off with camera',
      'Rechargeable battery',
    ],
    useCase: "Run-and-gun creators who don't want to clip a lav every shot.",
    imagePath: '/photos/gear/rode-videomic-pro-plus.jpg',
    aaronUses: false,
  },
  {
    slug: 'shure-mv7-plus',
    name: 'Shure MV7+',
    category: 'usb-mic',
    tier: 'growth',
    priceLow: 250,
    priceHigh: 270,
    brand: 'Shure',
    notes: 'USB + XLR hybrid. Touch panel. Auto-level technology.',
    why: [
      'USB and XLR in one mic (grow into pro setup)',
      "Auto-leveling so you don't blow the mix",
      'Touch panel controls (no fumbling)',
      'Broadcast-quality sound',
    ],
    useCase: 'Podcasters and desk-based creators who want broadcast sound without a separate audio interface.',
    imagePath: '/photos/gear/shure-mv7-plus.jpg',
    aaronUses: false,
  },
  {
    slug: 'elgato-key-light-air',
    name: 'Elgato Key Light Air (Pair)',
    category: 'lighting',
    tier: 'growth',
    priceLow: 260,
    priceHigh: 260,
    brand: 'Elgato',
    notes: '$130 each. Buy two for proper key + fill.',
    why: [
      'Desk-mount design (no light stands needed)',
      'App-controlled',
      '2800K to 7000K range',
      'Two-point lighting in one purchase',
    ],
    useCase: 'Permanent desk setup. Talking head creators who film in the same spot every time.',
    imagePath: '/photos/gear/elgato-key-light-air.jpg',
    aaronUses: true,
  },
  {
    slug: 'parrot-teleprompter-v3',
    name: 'Parrot Teleprompter V3',
    category: 'teleprompter',
    tier: 'growth',
    priceLow: 130,
    priceHigh: 160,
    brand: 'Parrot',
    notes: 'Mounts on camera lens. Professional delivery improvement.',
    why: [
      'Mounts directly on the camera lens',
      'Eyes stay on the lens (looks natural)',
      'Compatible with most cameras and phones',
      'Massive delivery upgrade vs reading off a tablet',
    ],
    useCase: 'Anyone scripting their videos who wants to ditch the awkward off-screen glance.',
    imagePath: '/photos/gear/parrot-teleprompter-v3.jpg',
    aaronUses: false,
  },
  {
    slug: 'sandisk-extreme-pro-128gb',
    name: 'SanDisk Extreme Pro 128GB',
    category: 'storage',
    tier: 'growth',
    priceLow: 20,
    priceHigh: 30,
    brand: 'SanDisk',
    notes: 'V30 speed rating minimum for 4K recording.',
    why: [
      'V30 minimum speed (required for 4K)',
      'Reliable, no dropped frames',
      'Industry standard',
      'Buy two so you always have a backup',
    ],
    useCase: "Mandatory for 4K recording. Don't cheap out on cards.",
    imagePath: '/photos/gear/sandisk-extreme-pro-128gb.jpg',
    aaronUses: false,
  },

  // ===== PRO TIER =====
  {
    slug: 'sony-a6700',
    name: 'Sony a6700',
    category: 'camera',
    tier: 'pro',
    priceLow: 1400,
    priceHigh: 1500,
    brand: 'Sony',
    notes: 'APS-C flagship. AI autofocus, 4K 120fps, pro-grade codecs.',
    why: [
      'AI-powered subject tracking (eye, face, body)',
      '4K at 120fps for slow-mo',
      'Professional codecs (S-Log3, ProRes-style)',
      'APS-C sensor (smaller, lighter, cheaper than full frame)',
    ],
    useCase: 'Channels with revenue, ready to commit to a pro body.',
    imagePath: '/photos/gear/sony-a6700.jpg',
    aaronUses: true,
  },
  {
    slug: 'sony-a7c-ii',
    name: 'Sony a7C II',
    category: 'camera',
    tier: 'pro',
    priceLow: 2100,
    priceHigh: 2200,
    brand: 'Sony',
    notes: 'Full-frame. Exceptional low-light. Future-proof investment.',
    why: [
      'Full-frame sensor (better low-light, shallower depth of field)',
      'Compact body for a full-frame',
      'Future-proof for years of channel growth',
      'Excellent autofocus',
    ],
    useCase: 'Creators committed to YouTube long-term who want top-tier image quality.',
    imagePath: '/photos/gear/sony-a7c-ii.jpg',
    aaronUses: true,
  },
  {
    slug: 'sigma-16mm-f14',
    name: 'Sigma 16mm f/1.4',
    category: 'lens',
    tier: 'pro',
    priceLow: 350,
    priceHigh: 400,
    brand: 'Sigma',
    notes: 'Talking-head hero lens',
    why: [
      'Fast aperture for creamy background blur',
      'Wide enough for handheld vlogging',
      'Sharp wide open',
      'The talking-head lens',
    ],
    useCase: "Talking head creators who want that 'cinematic' shallow depth of field look.",
    imagePath: '/photos/gear/sigma-16mm-f14.jpg',
    aaronUses: false,
  },
  {
    slug: 'tamron-17-70mm-f28',
    name: 'Tamron 17-70mm f/2.8',
    category: 'lens',
    tier: 'pro',
    priceLow: 750,
    priceHigh: 800,
    brand: 'Tamron',
    notes: 'All-in-one zoom',
    why: [
      'Constant f/2.8 across the entire zoom range',
      'Wide enough for room shots, long enough for tight portraits',
      'Property tours and talking head in one lens',
      'Excellent value for the focal range and aperture',
    ],
    useCase: 'Real estate creators, property tour channels, anyone who hates swapping lenses mid-shoot.',
    imagePath: '/photos/gear/tamron-17-70mm-f28.jpg',
    aaronUses: false,
  },
  {
    slug: 'shure-sm7b',
    name: 'Shure SM7B',
    category: 'dynamic-mic',
    tier: 'pro',
    priceLow: 350,
    priceHigh: 400,
    brand: 'Shure',
    notes: 'Industry standard broadcast mic. Requires audio interface.',
    why: [
      'The mic used by Joe Rogan, every podcast network, every radio station',
      'Rejects room noise extremely well',
      'Broadcast-quality vocal warmth',
      'Indestructible',
    ],
    useCase: 'Podcasters, talking head creators, anyone with a permanent recording space and a separate audio interface.',
    imagePath: '/photos/gear/shure-sm7b.jpg',
    aaronUses: false,
  },
  {
    slug: 'focusrite-scarlett-2i2',
    name: 'Focusrite Scarlett 2i2 (4th Gen)',
    category: 'accessory',
    tier: 'pro',
    priceLow: 170,
    priceHigh: 190,
    brand: 'Focusrite',
    notes: 'Pairs with SM7B. Clean preamps. USB-C.',
    why: [
      "Required if you're using the SM7B",
      'Clean, quiet preamps (great with low-output mics)',
      'USB-C connection',
      'Two inputs (interview-ready)',
    ],
    useCase: 'Mandatory partner for the Shure SM7B.',
    imagePath: '/photos/gear/focusrite-scarlett-2i2.jpg',
    aaronUses: false,
  },
  {
    slug: 'aputure-amaran-200d',
    name: 'Aputure Amaran 200d',
    category: 'lighting',
    tier: 'pro',
    priceLow: 250,
    priceHigh: 300,
    brand: 'Aputure',
    notes: 'Daylight-balanced LED. Professional 3-point lighting.',
    why: [
      '200W of daylight-balanced output',
      'High CRI for accurate color',
      'Bowens mount (works with all standard modifiers)',
      'Build quality of lights costing 3x as much',
    ],
    useCase: 'Anyone serious about three-point lighting. Serious cinematic look.',
    imagePath: '/photos/gear/aputure-amaran-200d.jpg',
    aaronUses: false,
  },
  {
    slug: 'dji-rs-4',
    name: 'DJI RS 4',
    category: 'gimbal',
    tier: 'pro',
    priceLow: 400,
    priceHigh: 500,
    brand: 'DJI',
    notes: 'Essential for property tours and walkthroughs',
    why: [
      '3-axis stabilization',
      'Holds full-frame mirrorless cameras',
      'Smooth tracking shots',
      'Game-changer for property tour content',
    ],
    useCase: 'Real estate, travel, vanlife, anyone whose content involves walking through spaces.',
    imagePath: '/photos/gear/dji-rs-4.jpg',
    aaronUses: true,
  },
  {
    slug: 'dji-mini-4-pro',
    name: 'DJI Mini 4 Pro',
    category: 'drone',
    tier: 'pro',
    priceLow: 760,
    priceHigh: 960,
    brand: 'DJI',
    notes: 'Under 249g. No Part 107 license needed for hobby use. 4K aerial.',
    why: [
      'Under 249g (no FAA registration needed for recreational use)',
      '4K video',
      'Obstacle sensing',
      'Excellent for property exteriors and B-roll',
    ],
    useCase: 'Real estate creators, travel/vanlife, anyone who wants aerial B-roll without commercial drone licensing.',
    imagePath: '/photos/gear/dji-mini-4-pro.jpg',
    aaronUses: true,
  },
  {
    slug: 'dji-osmo-pocket-3',
    name: 'DJI Osmo Pocket 3',
    category: 'camera',
    tier: 'pro',
    priceLow: 350,
    priceHigh: 520,
    brand: 'DJI',
    notes: 'Built-in gimbal. 16mm wide. Quick B-roll capture.',
    why: [
      'Built-in 3-axis gimbal (no external rig needed)',
      '1-inch sensor (better than most action cams)',
      'Pocket-sized',
      'The "always have it on you" camera for B-roll',
    ],
    useCase: "B-roll, behind-the-scenes, vlogging on the move. Aaron's @VanLife setup uses this heavily.",
    imagePath: '/photos/gear/dji-osmo-pocket-3.jpg',
    aaronUses: true,
  },

  // ===== LIVE STREAMING HARDWARE =====
  {
    slug: 'elgato-stream-deck-mk2',
    name: 'Elgato Stream Deck MK.2',
    category: 'streamdeck',
    tier: 'growth',
    priceLow: 150,
    priceHigh: 200,
    brand: 'Elgato',
    notes: 'Programmable LCD button panel. Switch scenes, mute mic, fire macros with one tap.',
    why: [
      '15 customizable LCD keys',
      'Built for OBS, Streamlabs, Twitch, YouTube Live',
      'Trigger AI prompts, copy snippets, control lights',
      'Becomes the brain of your stream',
    ],
    useCase: 'Live streamers, podcasters, anyone with multi-scene workflows. Cuts mid-stream chaos by 90 percent.',
    imagePath: '/photos/gear/elgato-stream-deck.jpg',
    aaronUses: true,
  },
  {
    slug: 'elgato-cam-link-4k',
    name: 'Elgato Cam Link 4K',
    category: 'accessory',
    tier: 'growth',
    priceLow: 110,
    priceHigh: 130,
    brand: 'Elgato',
    notes: 'Turns any HDMI camera into a 4K USB webcam.',
    why: [
      'Use your real camera as a webcam',
      'Plug-and-play USB-C',
      '4K passthrough at 30fps',
      'Works with OBS, Zoom, Streamyard, Restream',
    ],
    useCase: 'Anyone with a mirrorless camera who wants pro quality on streams or video calls.',
    imagePath: '/photos/gear/elgato-cam-link-4k.jpg',
    aaronUses: false,
  },
  {
    slug: 'elgato-facecam-pro',
    name: 'Elgato Facecam Pro',
    category: 'camera',
    tier: 'growth',
    priceLow: 280,
    priceHigh: 320,
    brand: 'Elgato',
    notes: '4K60 webcam built specifically for streamers and creators.',
    why: [
      'True 4K at 60fps',
      'Designed for live streaming, no driver headaches',
      'Better than any laptop or mirrorless-via-Cam-Link for plug-and-play',
      'Uncompressed video output',
    ],
    useCase: 'Streamers and creators who want studio quality without the mirrorless camera setup.',
    imagePath: '/photos/gear/elgato-facecam-pro.jpg',
    aaronUses: false,
  },
  {
    slug: 'elgato-wave-3',
    name: 'Elgato Wave:3',
    category: 'usb-mic',
    tier: 'growth',
    priceLow: 130,
    priceHigh: 170,
    brand: 'Elgato',
    notes: 'Premium USB condenser mic with software mixer.',
    why: [
      'Plug-and-play USB',
      'Built-in clipguard prevents distortion',
      'Wave Link app gives you software-level mixing',
      'Pairs with Stream Deck for full streaming control',
    ],
    useCase: 'Streamers who want one cable from mic to PC without an audio interface.',
    imagePath: '/photos/gear/elgato-wave-3.jpg',
    aaronUses: false,
  },

  // ===== SOFTWARE: VIDEO EDITING =====
  {
    slug: 'capcut-desktop',
    name: 'CapCut Desktop',
    category: 'software-editing',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 8,
    brand: 'ByteDance',
    notes: 'Free; Pro $8/mo',
    why: [
      'AI captions',
      'Built-in templates',
      'Auto-reframe for Shorts',
      'Free is genuinely usable',
    ],
    useCase: 'Beginners and Shorts-first creators. The fastest editor for simple cuts.',
    imagePath: '/photos/gear/capcut-desktop.jpg',
    aaronUses: false,
  },
  {
    slug: 'descript',
    name: 'Descript',
    category: 'software-editing',
    tier: 'growth',
    priceLow: 24,
    priceHigh: 33,
    brand: 'Descript',
    notes: '$24-33/mo',
    why: [
      'Edit video by editing text',
      'AI filler word removal',
      'Studio Sound noise removal (free with sub)',
      'Automatic transcription',
    ],
    useCase: 'Anyone who values speed and AI-assisted workflows over frame-perfect timeline control.',
    imagePath: '/photos/gear/descript.jpg',
    aaronUses: false,
  },
  {
    slug: 'davinci-resolve',
    name: 'DaVinci Resolve',
    category: 'software-editing',
    tier: 'pro',
    priceLow: 0,
    priceHigh: 295,
    brand: 'Blackmagic Design',
    notes: 'Free; Studio $295 one-time',
    why: [
      'Free version is genuinely professional',
      'Industry-leading color grading',
      'No subscription',
      'Fusion built in for VFX',
    ],
    useCase: "Editors who want pro tools without Adobe's monthly bill.",
    imagePath: '/photos/gear/davinci-resolve.jpg',
    aaronUses: false,
  },
  {
    slug: 'adobe-premiere-pro',
    name: 'Adobe Premiere Pro',
    category: 'software-editing',
    tier: 'pro',
    priceLow: 23,
    priceHigh: 23,
    brand: 'Adobe',
    notes: '$23/mo (Creative Cloud)',
    why: [
      'Industry standard',
      'Most plugins and integrations',
      'AI features via Firefly',
      'Steep learning curve',
    ],
    useCase: 'Pros, agencies, anyone collaborating with editors who use Premiere.',
    imagePath: '/photos/gear/adobe-premiere-pro.jpg',
    aaronUses: false,
  },
  {
    slug: 'final-cut-pro',
    name: 'Final Cut Pro',
    category: 'software-editing',
    tier: 'pro',
    priceLow: 300,
    priceHigh: 300,
    brand: 'Apple',
    notes: '$300 one-time',
    why: [
      'Magnetic timeline',
      'Optimized for Apple silicon',
      'Fast rendering',
      'One-time purchase',
    ],
    useCase: 'Mac users who want the fastest possible workflow on Apple hardware.',
    imagePath: '/photos/gear/final-cut-pro.jpg',
    aaronUses: false,
  },
  {
    slug: 'firecut',
    name: 'FireCut',
    category: 'software-editing',
    tier: 'growth',
    priceLow: 15,
    priceHigh: 30,
    brand: 'FireCut',
    notes: '$15-30/mo',
    why: [
      'AI auto-cuts inside Premiere Pro',
      'Silence removal',
      'Chapter detection',
    ],
    useCase: 'Premiere Pro users who want AI assist without leaving their existing workflow.',
    imagePath: '/photos/gear/firecut.jpg',
    aaronUses: false,
  },

  // ===== SOFTWARE: AI =====
  {
    slug: 'chatgpt',
    name: 'ChatGPT',
    category: 'software-ai',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 20,
    brand: 'OpenAI',
    notes: 'Free; Plus $20/mo',
    why: [
      'Content ideation, script outlines, title variations',
      'Massive plugin ecosystem',
      'Image generation built in',
      'The default for most people',
    ],
    useCase: 'Quick brainstorms, title variations, description drafts.',
    imagePath: '/photos/gear/chatgpt.jpg',
    aaronUses: false,
  },
  {
    slug: 'claude-anthropic',
    name: 'Claude',
    category: 'software-ai',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 20,
    brand: 'Anthropic',
    notes: 'Free; Pro $20/mo',
    why: [
      'Long-form writing',
      'Deep strategy work',
      'Document analysis',
      "Aaron's preferred AI for book-length and complex prompt chains",
    ],
    useCase: 'Writing strategy docs, book chapters, multi-step thinking.',
    imagePath: '/photos/gear/claude-anthropic.jpg',
    aaronUses: true,
  },
  {
    slug: 'google-gemini',
    name: 'Google Gemini',
    category: 'software-ai',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 20,
    brand: 'Google',
    notes: 'Free; Advanced $20/mo',
    why: [
      'Multimodal (text + image + video)',
      'Integrated with Google ecosystem',
      'Real-time data access',
    ],
    useCase: 'Research with sources. Analyzing competitor videos. Image-based research.',
    imagePath: '/photos/gear/google-gemini.jpg',
    aaronUses: false,
  },
  {
    slug: 'perplexity-ai',
    name: 'Perplexity AI',
    category: 'software-ai',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 20,
    brand: 'Perplexity',
    notes: 'Free; Pro $20/mo',
    why: [
      'Sourced research with citations',
      'Real-time data',
      'Designed for research, not chat',
    ],
    useCase: 'Researching script content where you need to cite real, current sources.',
    imagePath: '/photos/gear/perplexity-ai.jpg',
    aaronUses: false,
  },
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    category: 'software-ai',
    tier: 'growth',
    priceLow: 5,
    priceHigh: 99,
    brand: 'ElevenLabs',
    notes: '$5-99/mo',
    why: [
      'Clone your own voice',
      'Voiceovers for B-roll without re-recording',
      'Multi-language support',
      'Best AI voice quality available',
    ],
    useCase: 'Voiceovers for B-roll, repurposing into other languages, faceless channels.',
    imagePath: '/photos/gear/elevenlabs.jpg',
    aaronUses: false,
  },
  {
    slug: 'adobe-podcast-ai',
    name: 'Adobe Podcast AI',
    category: 'software-ai',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 0,
    brand: 'Adobe',
    notes: 'Free (web-based)',
    why: [
      'Free',
      'Cleans up bad audio after the fact',
      'Dead simple (upload, download)',
    ],
    useCase: 'Anyone who recorded audio in a less-than-ideal space and needs to fix it.',
    imagePath: '/photos/gear/adobe-podcast-ai.jpg',
    aaronUses: false,
  },
  {
    slug: 'midjourney',
    name: 'Midjourney',
    category: 'software-ai',
    tier: 'growth',
    priceLow: 10,
    priceHigh: 30,
    brand: 'Midjourney',
    notes: '$10-30/mo',
    why: [
      'Best AI image quality available',
      'Custom thumbnail backgrounds',
      'Conceptual B-roll imagery',
    ],
    useCase: "Creators who need custom imagery they can't shoot themselves.",
    imagePath: '/photos/gear/midjourney.jpg',
    aaronUses: false,
  },

  // ===== SOFTWARE: REPURPOSE =====
  {
    slug: 'opusclip',
    name: 'OpusClip',
    category: 'software-repurpose',
    tier: 'growth',
    priceLow: 19,
    priceHigh: 49,
    brand: 'OpusClip',
    notes: '$19-49/mo',
    why: [
      'AI auto-extracts the best moments from long-form',
      'Generates 10-15 viral-scored Shorts per video',
      'Auto-captions',
      'Reframes to vertical',
    ],
    useCase: 'Repurposing long-form into Shorts without manual editing time.',
    imagePath: '/photos/gear/opusclip.jpg',
    aaronUses: false,
  },
  {
    slug: 'vidyo-ai',
    name: 'Vidyo.ai',
    category: 'software-repurpose',
    tier: 'growth',
    priceLow: 30,
    priceHigh: 50,
    brand: 'Vidyo.ai',
    notes: '$30-50/mo',
    why: [
      'Alternative to OpusClip',
      'Good for batch processing multiple videos at once',
      'Different scoring algorithm (sometimes finds different clips)',
    ],
    useCase: 'Agencies and creators repurposing high volume.',
    imagePath: '/photos/gear/vidyo-ai.jpg',
    aaronUses: false,
  },
  {
    slug: 'revid-ai',
    name: 'Revid.ai',
    category: 'software-repurpose',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 29,
    brand: 'Revid.ai',
    notes: 'Free; Pro up to $29/mo',
    why: [
      'Text-to-video Shorts',
      'Auto Mode generates daily content',
      'Good for faceless niches',
    ],
    useCase: 'Faceless channel operators or creators who want a content stream without filming.',
    imagePath: '/photos/gear/revid-ai.jpg',
    aaronUses: false,
  },
  {
    slug: 'riverside-fm',
    name: 'Riverside.fm',
    category: 'software-repurpose',
    tier: 'growth',
    priceLow: 19,
    priceHigh: 29,
    brand: 'Riverside.fm',
    notes: '$19-29/mo',
    why: [
      'Records remote interviews with separate tracks',
      'Local recording (no internet quality issues)',
      'AI Magic Clips for short-form',
    ],
    useCase: 'Anyone recording remote interviews or guest content.',
    imagePath: '/photos/gear/riverside-fm.jpg',
    aaronUses: false,
  },
  {
    slug: 'buffer-hootsuite',
    name: 'Buffer / Hootsuite',
    category: 'software-repurpose',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 15,
    brand: 'Buffer or Hootsuite',
    notes: 'Free tier; Pro from $15/mo',
    why: [
      'Schedule across Instagram, X, LinkedIn, Facebook',
      'Set and forget',
      'Both have generous free tiers',
    ],
    useCase: 'Cross-platform repurposing without daily manual posting.',
    imagePath: '/photos/gear/buffer-hootsuite.jpg',
    aaronUses: false,
  },

  // ===== SOFTWARE: GROWTH (design, thumbnails, automation, youtube tools, planning) =====
  {
    slug: 'canva-pro',
    name: 'Canva Pro',
    category: 'software-growth',
    tier: 'starter',
    priceLow: 13,
    priceHigh: 13,
    brand: 'Canva',
    notes: '$13/mo',
    why: [
      'Thumbnail templates',
      'Magic Eraser',
      'Background removal',
      'Brand kit',
      'Easy enough for non-designers',
    ],
    useCase: "Thumbnail creation if you're not in Photoshop. Brand asset creation.",
    imagePath: '/photos/gear/canva-pro.jpg',
    aaronUses: false,
  },
  {
    slug: 'photoshop',
    name: 'Photoshop',
    category: 'software-growth',
    tier: 'pro',
    priceLow: 23,
    priceHigh: 23,
    brand: 'Adobe',
    notes: '$23/mo (Creative Cloud)',
    why: [
      'Generative Fill for backgrounds',
      'Professional compositing',
      'Industry standard for thumbnail designers',
    ],
    useCase: 'Anyone hiring a designer or doing pro-level thumbnails themselves.',
    imagePath: '/photos/gear/photoshop.jpg',
    aaronUses: false,
  },
  {
    slug: 'pikzels',
    name: 'Pikzels',
    category: 'software-growth',
    tier: 'growth',
    priceLow: 9,
    priceHigh: 29,
    brand: 'Pikzels',
    notes: '$9-29/mo',
    why: [
      'Scores thumbnail effectiveness before publishing',
      'Predicts CTR',
      'Compares variants',
    ],
    useCase: 'Channels with traffic where small CTR improvements move the needle.',
    imagePath: '/photos/gear/pikzels.jpg',
    aaronUses: false,
  },
  {
    slug: 'remove-bg',
    name: 'Remove.bg',
    category: 'software-growth',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 10,
    brand: 'Remove.bg',
    notes: 'Free; Pro up to $10/mo',
    why: [
      'One-click background removal',
      'Web-based, no install',
      'Cheap or free',
    ],
    useCase: 'Cutting out subjects for thumbnails. Quick one-off background removal.',
    imagePath: '/photos/gear/remove-bg.jpg',
    aaronUses: false,
  },
  {
    slug: 'n8n',
    name: 'N8N',
    category: 'software-growth',
    tier: 'growth',
    priceLow: 0,
    priceHigh: 24,
    brand: 'N8N',
    notes: 'Free (self-hosted); Cloud from $24/mo',
    why: [
      'Open source',
      "Aaron's primary automation engine",
      'AI avatar generation',
      'Automated posting and content pipelines',
    ],
    useCase: 'Builders who want full control of their automation stack without per-zap pricing.',
    imagePath: '/photos/gear/n8n.jpg',
    aaronUses: true,
  },
  {
    slug: 'zapier',
    name: 'Zapier',
    category: 'software-growth',
    tier: 'growth',
    priceLow: 20,
    priceHigh: 70,
    brand: 'Zapier',
    notes: '$20-70/mo',
    why: [
      'Largest integration library',
      'Connects GoHighLevel, Skool, email, YouTube',
      'No code required',
    ],
    useCase: 'Quick wins where you need two tools talking to each other now.',
    imagePath: '/photos/gear/zapier.jpg',
    aaronUses: false,
  },
  {
    slug: 'make-com',
    name: 'Make.com',
    category: 'software-growth',
    tier: 'growth',
    priceLow: 9,
    priceHigh: 29,
    brand: 'Make.com',
    notes: '$9-29/mo',
    why: [
      'More flexible than Zapier for complex flows',
      'Visual builder with branching logic',
      'Cheaper at scale',
    ],
    useCase: 'Multi-step scenarios that Zapier struggles with.',
    imagePath: '/photos/gear/make-com.jpg',
    aaronUses: false,
  },
  {
    slug: 'tubebuddy',
    name: 'TubeBuddy',
    category: 'software-growth',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 8,
    brand: 'TubeBuddy',
    notes: 'Free; Pro from $8/mo',
    why: [
      'Keyword Explorer',
      'Tag suggestions',
      'Thumbnail A/B testing',
      'The one tool every creator should install',
    ],
    useCase: 'Mandatory for anyone serious about YouTube SEO.',
    imagePath: '/photos/gear/tubebuddy.jpg',
    aaronUses: false,
  },
  {
    slug: 'vidiq',
    name: 'VidIQ',
    category: 'software-growth',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 17,
    brand: 'VidIQ',
    notes: 'Free; Pro from $17/mo',
    why: [
      'Views Per Hour tracking',
      'Competitor analysis',
      'Daily Ideas (algorithmic suggestions)',
      'AI Coach',
    ],
    useCase: 'Complement to TubeBuddy. Different signals, both useful.',
    imagePath: '/photos/gear/vidiq.jpg',
    aaronUses: false,
  },
  {
    slug: 'viewstats',
    name: 'ViewStats',
    category: 'software-growth',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 10,
    brand: "ViewStats (MrBeast's team)",
    notes: 'Free; Pro from $10/mo',
    why: [
      '2,500x more data points than competitors',
      'Viral prediction',
      'Built by people running 100M+ sub channels',
    ],
    useCase: 'Channels chasing the algorithm at scale.',
    imagePath: '/photos/gear/viewstats.jpg',
    aaronUses: false,
  },
  {
    slug: 'social-blade',
    name: 'Social Blade',
    category: 'software-growth',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 0,
    brand: 'Social Blade',
    notes: 'Free',
    why: [
      'Public channel analytics',
      'Competitor growth tracking',
      'Free',
    ],
    useCase: 'Spying on competitors. Tracking your own growth rate over time.',
    imagePath: '/photos/gear/social-blade.jpg',
    aaronUses: false,
  },
  {
    slug: 'poppy-ai',
    name: 'Poppy AI',
    category: 'software-growth',
    tier: 'growth',
    priceLow: 15,
    priceHigh: 40,
    brand: 'Poppy AI',
    notes: '$15-40/mo',
    why: [
      'Analyze competitor videos',
      'Generate scripts in your voice',
      'Hook templates',
    ],
    useCase: 'Channels copying winning competitor formats fast.',
    imagePath: '/photos/gear/poppy-ai.jpg',
    aaronUses: false,
  },
  {
    slug: 'notion',
    name: 'Notion',
    category: 'software-growth',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 10,
    brand: 'Notion',
    notes: 'Free; Plus from $10/mo',
    why: [
      'Content calendars',
      'Video databases',
      'SOPs',
      "Aaron's 'second brain'",
    ],
    useCase: 'Solo creators and teams managing content pipelines.',
    imagePath: '/photos/gear/notion.jpg',
    aaronUses: false,
  },
  {
    slug: 'trello',
    name: 'Trello',
    category: 'software-growth',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 10,
    brand: 'Atlassian',
    notes: 'Free; Standard from $10/mo',
    why: [
      'Kanban boards',
      'Visual workflow management',
      'Idea, Script, Film, Edit, Publish pipelines',
    ],
    useCase: 'Visual thinkers who want a simple kanban for their video pipeline.',
    imagePath: '/photos/gear/trello.jpg',
    aaronUses: false,
  },

  // ===== SOFTWARE: LEAD GEN =====
  {
    slug: 'gohighlevel',
    name: 'GoHighLevel',
    category: 'software-leadgen',
    tier: 'pro',
    priceLow: 97,
    priceHigh: 297,
    brand: 'GoHighLevel',
    notes: '$97-297/mo',
    why: [
      "Aaron's primary CRM (already in his stack)",
      'Landing pages, email sequences, pipeline management, appointment booking in one',
      'Replaces 5+ tools',
    ],
    useCase: 'Anyone running a real business through YouTube. The complete back-end.',
    imagePath: '/photos/gear/gohighlevel.jpg',
    aaronUses: true,
  },
  {
    slug: 'skool',
    name: 'Skool',
    category: 'software-leadgen',
    tier: 'growth',
    priceLow: 99,
    priceHigh: 99,
    brand: 'Skool',
    notes: '$99/mo',
    why: [
      'Courses + community in one',
      "Where Aaron's coaching members live",
      'Gamification built in',
    ],
    useCase: 'Anyone monetizing community access. Where the Crazy Simple YouTube community lives.',
    imagePath: '/photos/gear/skool.jpg',
    aaronUses: true,
  },
  {
    slug: 'calendly',
    name: 'Calendly',
    category: 'software-leadgen',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 12,
    brand: 'Calendly',
    notes: 'Free; Pro from $12/mo',
    why: [
      'Embed in YouTube descriptions',
      'Reduces scheduling friction to zero',
      'Integrates with everything',
    ],
    useCase: 'Mandatory if you want viewers to book calls.',
    imagePath: '/photos/gear/calendly.jpg',
    aaronUses: false,
  },
  {
    slug: 'convertkit-kit',
    name: 'Kit (formerly ConvertKit)',
    category: 'software-leadgen',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 29,
    brand: 'Kit',
    notes: 'Free; Creator Pro from $29/mo',
    why: [
      'Visual automation builder',
      'Creator-focused (built for newsletters and digital products)',
      'Good free tier',
    ],
    useCase: "If you're not using GoHighLevel yet. Email-only setup.",
    imagePath: '/photos/gear/convertkit-kit.jpg',
    aaronUses: false,
  },
  {
    slug: 'leadpages',
    name: 'Leadpages',
    category: 'software-leadgen',
    tier: 'growth',
    priceLow: 37,
    priceHigh: 74,
    brand: 'Leadpages',
    notes: '$37-74/mo',
    why: [
      'Standalone landing pages',
      'Conversion-tested templates',
      'Faster than building from scratch',
    ],
    useCase: 'When you need a quick landing page outside your main CRM.',
    imagePath: '/photos/gear/leadpages.jpg',
    aaronUses: false,
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    category: 'software-leadgen',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 0,
    brand: 'Stripe',
    notes: '2.9% + $0.30 per transaction',
    why: [
      'Connects to GoHighLevel and Skool',
      'Handles subscriptions and one-time payments',
      'Industry standard',
    ],
    useCase: 'Mandatory for collecting money online.',
    imagePath: '/photos/gear/stripe.jpg',
    aaronUses: false,
  },
  {
    slug: 'carrd',
    name: 'Carrd',
    category: 'software-leadgen',
    tier: 'starter',
    priceLow: 0,
    priceHigh: 19,
    brand: 'Carrd',
    notes: 'Free; Pro $19/year',
    why: [
      'Quick one-page websites',
      'Dead simple setup',
      'Cheap',
    ],
    useCase: 'Link-in-bio pages, single lead magnets, simple landing pages.',
    imagePath: '/photos/gear/carrd.jpg',
    aaronUses: false,
  },
]
