export type WorksheetPart =
  | 'Foundation'
  | 'Content Creation'
  | 'Business of YouTube'
  | 'Scale and Sustainability'

export interface Worksheet {
  slug: string
  chapter: number
  title: string
  part: WorksheetPart
  timeMinutes: number
  caseStudyPerson: string
  shortDesc: string
}

export const worksheets: Worksheet[] = [
  {
    slug: '01-calculate-your-youtube-hourly-rate',
    chapter: 1,
    title: 'Calculate Your YouTube Hourly Rate',
    part: 'Foundation',
    timeMinutes: 5,
    caseStudyPerson: '',
    shortDesc: 'Calculate the real dollar value of every hour you spend creating YouTube content.',
  },
  {
    slug: '02-the-myth-detox',
    chapter: 2,
    title: 'The Myth Detox',
    part: 'Foundation',
    timeMinutes: 5,
    caseStudyPerson: 'Daniel',
    shortDesc: 'Audit the YouTube advice you have been following and drop the myths holding you back.',
  },
  {
    slug: '03-your-algorithm-health-check',
    chapter: 3,
    title: 'Your Algorithm Health Check',
    part: 'Foundation',
    timeMinutes: 30,
    caseStudyPerson: '',
    shortDesc: 'Diagnose your channel bottleneck by scoring CTR, retention, and watch time on recent videos.',
  },
  {
    slug: '04-map-your-revenue-path',
    chapter: 4,
    title: 'Map Your Revenue Path',
    part: 'Foundation',
    timeMinutes: 10,
    caseStudyPerson: 'Sarah',
    shortDesc: 'Map a clear path from YouTube viewer to paying client with a lead magnet and follow-up plan.',
  },
  {
    slug: '05-your-10-minute-equipment-audit',
    chapter: 5,
    title: 'Your 10-Minute Equipment Audit',
    part: 'Foundation',
    timeMinutes: 10,
    caseStudyPerson: '',
    shortDesc: 'Confirm you already have everything you need to start filming and lock in your first shoot date.',
  },
  {
    slug: '06-your-one-hour-channel-makeover',
    chapter: 6,
    title: 'Your One-Hour Channel Makeover',
    part: 'Foundation',
    timeMinutes: 60,
    caseStudyPerson: '',
    shortDesc: 'Overhaul your channel name, banner, about section, and playlists in a single focused hour.',
  },
  {
    slug: '07-the-30-minute-topic-bank-builder',
    chapter: 7,
    title: 'The 30-Minute Topic Bank Builder',
    part: 'Content Creation',
    timeMinutes: 30,
    caseStudyPerson: '',
    shortDesc: 'Build a validated bank of video topics and pick your next four with confidence.',
  },
  {
    slug: '08-the-title-and-thumbnail-audit',
    chapter: 8,
    title: 'The Title and Thumbnail Audit',
    part: 'Content Creation',
    timeMinutes: 30,
    caseStudyPerson: '',
    shortDesc: 'Find the pattern that separates your best titles and thumbnails from your worst, then rewrite.',
  },
  {
    slug: '09-the-hook-audit-and-rebuild',
    chapter: 9,
    title: 'The Hook Audit and Rebuild',
    part: 'Content Creation',
    timeMinutes: 30,
    caseStudyPerson: 'Daniel',
    shortDesc: 'Diagnose weak openings and build a hook template that holds viewers past the first 30 seconds.',
  },
  {
    slug: '10-build-your-retention-blueprint',
    chapter: 10,
    title: 'Build Your Retention Blueprint',
    part: 'Content Creation',
    timeMinutes: 30,
    caseStudyPerson: 'Jennifer',
    shortDesc: 'Plan value peaks, open loops, and pattern interrupts so viewers stay to the end.',
  },
  {
    slug: '11-find-your-scripting-sweet-spot',
    chapter: 11,
    title: 'Find Your Scripting Sweet Spot',
    part: 'Content Creation',
    timeMinutes: 30,
    caseStudyPerson: 'Marcus',
    shortDesc: 'Build a reusable outline and pre-recording ritual so you can deliver naturally on camera.',
  },
  {
    slug: '12-build-your-editing-template',
    chapter: 12,
    title: 'Build Your Editing Template',
    part: 'Content Creation',
    timeMinutes: 45,
    caseStudyPerson: 'Marcus',
    shortDesc: 'Cut your editing time by building a reusable template and capping the time per video.',
  },
  {
    slug: '13-build-your-launch-checklist',
    chapter: 13,
    title: 'Build Your Launch Checklist',
    part: 'Business of YouTube',
    timeMinutes: 20,
    caseStudyPerson: 'Rachel',
    shortDesc: 'Lock in pre-publish and post-publish checklists so every upload gets its best shot.',
  },
  {
    slug: '14-build-your-sustainable-system',
    chapter: 14,
    title: 'Build Your Sustainable System',
    part: 'Business of YouTube',
    timeMinutes: 30,
    caseStudyPerson: 'Mike',
    shortDesc: 'Design a realistic publishing rhythm that survives your busiest seasons.',
  },
  {
    slug: '15-your-first-analytics-audit',
    chapter: 15,
    title: 'Your First Analytics Audit',
    part: 'Business of YouTube',
    timeMinutes: 30,
    caseStudyPerson: 'Kevin',
    shortDesc: 'Set a 28-day baseline, identify your primary problem, and schedule a weekly review habit.',
  },
  {
    slug: '16-build-your-shorts-strategy',
    chapter: 16,
    title: 'Build Your Shorts Strategy',
    part: 'Business of YouTube',
    timeMinutes: 30,
    caseStudyPerson: 'Lisa',
    shortDesc: 'Decide the role of Shorts on your channel and queue five from existing long-form videos.',
  },
  {
    slug: '17-build-your-lead-system-this-week',
    chapter: 17,
    title: 'Build Your Lead System This Week',
    part: 'Business of YouTube',
    timeMinutes: 90,
    caseStudyPerson: 'Sandra',
    shortDesc: 'Launch a complete lead magnet, capture page, and five-email welcome sequence in seven days.',
  },
  {
    slug: '18-optimize-your-sales-conversation',
    chapter: 18,
    title: 'Optimize Your Sales Conversation',
    part: 'Business of YouTube',
    timeMinutes: 45,
    caseStudyPerson: 'Robert',
    shortDesc: 'Build a discovery, presentation, and objection framework that turns YouTube leads into clients.',
  },
  {
    slug: '19-prepare-to-scale',
    chapter: 19,
    title: 'Prepare to Scale',
    part: 'Scale and Sustainability',
    timeMinutes: 45,
    caseStudyPerson: 'Amanda',
    shortDesc: 'Assess readiness, identify your first hire, and run a paid test project on a clear timeline.',
  },
  {
    slug: '20-build-your-resilience-system',
    chapter: 20,
    title: 'Build Your Resilience System',
    part: 'Scale and Sustainability',
    timeMinutes: 20,
    caseStudyPerson: 'Leah',
    shortDesc: 'Set analytics boundaries, build a support network, and commit to publishing 100 videos.',
  },
  {
    slug: '21-launch-your-community-strategy',
    chapter: 21,
    title: 'Launch Your Community Strategy',
    part: 'Scale and Sustainability',
    timeMinutes: 50,
    caseStudyPerson: 'Elena',
    shortDesc: 'Define your community identity, set engagement slots, and plan two weeks of community posts.',
  },
  {
    slug: '22-build-your-repurposing-system',
    chapter: 22,
    title: 'Build Your Repurposing System',
    part: 'Scale and Sustainability',
    timeMinutes: 45,
    caseStudyPerson: 'David',
    shortDesc: 'Pick two platforms, define your workflow, and repurpose your last video before you stop.',
  },
  {
    slug: '23-build-your-tracking-system-today',
    chapter: 23,
    title: 'Build Your Tracking System Today',
    part: 'Scale and Sustainability',
    timeMinutes: 55,
    caseStudyPerson: 'Marcus',
    shortDesc: 'Set up source tracking, baseline your numbers, and calculate your starting YouTube ROI.',
  },
  {
    slug: '24-your-commitment',
    chapter: 24,
    title: 'Your Commitment',
    part: 'Scale and Sustainability',
    timeMinutes: 15,
    caseStudyPerson: 'Scott',
    shortDesc: 'Sign a 90-day pledge that locks in your why, schedule, actions, and accountability plan.',
  },
]
