export interface WorksheetContext {
  chapter: number
  why: string
  aaronNote: string
  caseStudyBlurb: string
}

export const worksheetContext: WorksheetContext[] = [
  {
    chapter: 1,
    why: 'Most business owners treat YouTube like a hobby because they have never actually done the math. Five minutes with a pen will change that. When you calculate what one video is worth over its lifetime (the leads, the clients, the commissions), the "I do not have time" excuse evaporates. This worksheet anchors you to a real number you can stick on a sticky note and stare at on the days you do not feel like hitting record. YouTube is not a time expense. It is a time investment. Prove it to yourself.',
    aaronNote: 'YouTube is not a time expense. It is a time investment. A clear process, repeated consistently, that builds something bigger than any ad campaign or networking event ever could. Write your YouTube Hourly Rate on a sticky note and look at it every day. Then press record anyway.',
    caseStudyBlurb: 'Marcus, a real estate agent in Austin, skipped a Saturday open house in 2019 and spent forty-five minutes on his iPhone making one neighborhood video. No ring light, no plan. Six years later that single video has produced over $387,000 in closed commissions and still generates leads while he sleeps. Proof that crazy simple, done once, beats overproduced never.'
  },
  {
    chapter: 2,
    why: 'Most of what you have heard about YouTube is wrong. Daily posting, subscriber chasing, expensive gear, two-minute videos, viral hits, blaming the algorithm. Every one of those myths is quietly torching your growth. This worksheet is a detox. You write down the rules you have been following, find out where they actually came from, and cut one loose before it costs you another six months. It is not busywork. It is the reset that makes every chapter after this one actually stick.',
    aaronNote: 'Stop blaming the algorithm. Start studying what it rewards. Those are two very different mindsets, and only one of them will grow your channel. Every myth you carry into your strategy is dead weight. Drop it now so the rest of the system can do its job.',
    caseStudyBlurb: 'Daniel, a consultant in Prague, spent six months posting three times a week chasing trending topics. He had 247 subscribers and zero clients. We dropped him to one weekly video answering the questions his ideal clients were searching for, swapped clever titles for searchable ones, and tracked retention instead of subscribers. Within 90 days his average view duration jumped from 1:45 to 6:30 and the consulting leads started showing up.'
  },
  {
    chapter: 3,
    why: 'The 2026 algorithm is not a mystery. It is a system with five inputs (CTR, AVD, watch time, engagement, session continuation), and once you can see your own numbers honestly, the path forward becomes obvious. This worksheet forces you to pull your last five videos, score them against real benchmarks, and pick the single biggest bottleneck holding the algorithm back from promoting you. No more guessing. No more shouting at YouTube. Just a clear diagnosis and one specific thing to attack in your next video.',
    aaronNote: 'The algorithm rewards clarity of purpose. Know your weak point. Attack it. Measure the results. That is how you turn the algorithm from something you fear into the most powerful marketing tool in your business.',
    caseStudyBlurb: 'A Colorado real estate agent had been posting consistently for six months and was stuck at 500 to 800 views per video. His CTR was 2.8%, AVD was 34%. We rebuilt his thumbnails, cut the 30-second intros, added pattern interrupts every 90 seconds, and pushed length from 8 to 18 minutes. Within 60 days his impressions doubled. Within 90, they tripled. Subscriber growth went from 100 to 400 per month.'
  },
  {
    chapter: 4,
    why: 'Plenty of creators have a YouTube channel. Almost none of them have a YouTube business model. That is the difference between a channel that produces nice comments and one that pays your bills. This worksheet drags you through five questions (your model, your lead magnet, your landing page, your follow-up, your conversion target) that turn vague intentions into a working revenue path. Most creators never do this. That is exactly why most creators do not make money. You are about to skip that mistake.',
    aaronNote: 'A YouTube channel without a business model is a hobby. You might get encouraging comments and a slow trickle of subscribers, but unless you have designed a system that turns viewers into leads and leads into clients, you are building a beautiful bridge to nowhere.',
    caseStudyBlurb: 'Sarah, a real estate agent in a Southern market, had 1,800 subscribers and zero dollars from eight months of posting. No CTAs, no lead magnet, just a homepage link in her descriptions. We built a neighborhood comparison guide, a dedicated landing page, a verbal CTA she used in every video, and a three-email sequence. Within 30 days she generated 47 leads. By month six, over $140,000 in commissions.'
  },
  {
    chapter: 5,
    why: 'Equipment is the most popular form of procrastination in YouTube. "I will start when I have the right camera" is just fear wearing a productive mask. This worksheet kills the gear excuse in ten minutes. If you own a smartphone, earbuds with a mic, a window, and something to prop your phone up, you have everything you need to build a six-figure channel. The audit forces you to admit it, name the real obstacle (which is almost never gear), and pick a specific date to film. That is the only upgrade that matters.',
    aaronNote: 'The equipment that matters most is the equipment that reduces friction. A complicated setup you avoid using is infinitely worse than a simple setup you use every day. Consistency builds channels. Not cameras.',
    caseStudyBlurb: 'A real estate investor and educator built a 200,000-subscriber channel and a seven-figure business on an iPhone 8, the earbuds that came in the box, and natural light. No face on camera, basic Canva intro, two videos a week for three years straight. He eventually upgraded to an iPhone 12 and a $30 lapel mic. That is the entire gear list behind the empire.'
  },
  {
    chapter: 6,
    why: 'Your channel page is your storefront, and right now it is probably costing you subscribers on every video you publish. Visitors decide in five seconds: what is this about, can I trust this person, what should I watch next? If your banner, photo, description, and playlists do not answer those three questions instantly, people bounce. This worksheet is a one-hour makeover. You do it once, and it pays you back on every future upload. Optimized channels convert visitors at 3 to 5 times the rate of unoptimized ones. Same content. Different storefront.',
    aaronNote: 'Clever is the enemy of clear. Cute channel names, artsy banners, witty descriptions, all of that kills conversions. Some of the biggest wins on YouTube are the unglamorous foundational stuff nobody wants to talk about.',
    caseStudyBlurb: 'A mortgage broker was getting 2,000 to 5,000 views per video but stuck at 1,200 subscribers. His channel page was a logo, a stock photo banner, and 47 random videos. We rebuilt every element in 90 minutes: real name, headshot, banner with a clear promise, five organized playlists, and a 75-second trailer. Within 60 days his subscriber conversion tripled, jumping from 40 to 50 per month to 150 to 200.'
  },
  {
    chapter: 7,
    why: 'YouTube is a search engine. If your video is not the answer to something someone is actually searching for, it sits in the void. Most creators make videos about whatever they were thinking about that week, then wonder why nothing happens. This worksheet flips you from creator to librarian. In 30 minutes you will pull 15 plus validated topics straight from YouTube autocomplete, steal proven winners from your competitors, mine your own client conversations, and pick four topics with real demand. No more guessing what people want.',
    aaronNote: 'Stop thinking like a content creator. Start thinking like a librarian. A librarian does not write books about whatever they find interesting. They stock books that patrons are looking for. Your job is the same: figure out what your audience is searching for, then create the best possible answer.',
    caseStudyBlurb: 'A Phoenix realtor had 67 videos and 340 subscribers because every title was about her ("My Journey Into Real Estate", "A Fun Day at the Office"). We did 30 minutes of alphabet soup research and her next video, "Moving to Phoenix in 2026: Pros and Cons from a Local Realtor", got 8,400 views in 60 days. Six months later: 4,100 subscribers and $214,000 in commissions from YouTube leads.'
  },
  {
    chapter: 8,
    why: 'Your title and thumbnail are not decorations. They are the marketing campaign for your video. YouTube can show your work to a million people, but if the packaging does not stop the scroll, nobody clicks and your video might as well not exist. This worksheet has you sort your existing videos by CTR, find the pattern between your winners and losers, and rewrite the titles and thumbnails on your three worst performers right now. Highest-ROI 30 minutes you will spend all month, because you are improving content that already exists.',
    aaronNote: 'A great title does three things at once: it promises a clear benefit, creates curiosity, and matches search intent. Specificity signals value. Vagueness signals boredom. Always write at least three title options. Your third or fourth, after pushing past the obvious, is almost always the winner.',
    caseStudyBlurb: 'A Texas mortgage broker had a "Mortgage Rate Update December" video sitting at 847 views and a "Mortgage Rates Just Dropped: Should You Refinance NOW?" video at 34,000. Same content quality. We spent an afternoon repackaging titles and thumbnails on his 15 worst performers. Within 90 days the average CTR on those videos went from 2.1% to 5.8%, and combined views jumped from 12,000 to over 67,000.'
  },
  {
    chapter: 9,
    why: 'You won the click. Now you have eight seconds before the average viewer decides whether to stay or bail. Generic greetings, subscribe begs, long intros, and apology openings are killing your retention before you even get to the value. This worksheet pulls up the retention graphs on your last three videos, diagnoses your 30-second drop-off, and rebuilds your hook using one of eight proven formulas. Strong openings cascade through everything: better retention, more promotion, more views, more leads. Master the first 30 seconds and the rest of the video has a fighting chance.',
    aaronNote: 'Your opening is not a formality. It is not a greeting. It is not a place to remind people to subscribe. Your opening is an audition. Every second, your viewer is subconsciously asking, "Is this worth my time?" Your hook must answer that question with a resounding yes before they finish asking it.',
    caseStudyBlurb: 'Daniel, the Prague consultant from Chapter 2, had a 32-second intro that started with "Hey everyone, welcome back to my channel" and ended with viewers already gone. We rebuilt his openings using the Problem-Agitate-Promise formula. Over 90 days his AVD climbed from 35% to 52%, 30-second retention went from 55% to 78%, and subscriber growth jumped from 400 to 1,200 per month.'
  },
  {
    chapter: 10,
    why: 'You nailed the hook. Now around the three-minute mark, viewers start trickling away and your retention graph turns into a playground slide. The sagging middle kills more videos than bad lighting ever will. This worksheet builds your retention architecture before you film: pick a structure (Countdown, Problem-Solution, Story Arc, or Tutorial), map five value peaks across the video, plan six pattern interrupts spaced 60 to 90 seconds apart, and identify your danger zones. Viewers do not watch videos. They watch moments. Build the moments.',
    aaronNote: 'Viewers do not watch videos. They watch moments. Your job is not to fill time. It is to create a sequence of moments that are each individually compelling, while building toward a satisfying conclusion. Every minute of your video needs to earn the next minute.',
    caseStudyBlurb: 'Jennifer, a real estate coach, was making 15-minute market updates that bled out to 25% retention by the end. We restructured her sequential data dumps into hook plus three deep-dive segments, each illustrated with a client story, with the "shocking stat" held until the 9-minute mark. Over 90 days AVD climbed from 38% to 54%, 10-minute retention went from 40% to 62%, and impressions increased 2.4 times.'
  },
  {
    chapter: 11,
    why: 'You do not need to be naturally charismatic on camera. You need a system. Most business pros freeze, ramble, sound robotic, or quit because they think on-camera presence is a fixed trait. It is not. It is a skill, and this worksheet builds your personal scripting and delivery system: pick your spot on the scripting spectrum (most people belong at "detailed outline"), build a reusable template, design your five-minute pre-recording ritual, and film a practice video this week. The awkwardness fades as the reps stack up. The system gets you reps without quitting first.',
    aaronNote: 'Great YouTube delivery is not about performing. It is about communicating clearly with energy. You are not trying to be a TV host. You are trying to be the most engaging version of yourself, explaining something you genuinely know and care about to someone who genuinely wants to learn it.',
    caseStudyBlurb: 'Marcus, a financial advisor, had quit YouTube three times because full scripts made him sound like he was reading a legal document. We moved him to detailed outlines, built a pre-recording ritual, put a real client photo next to his lens, and broke his addiction to perfect takes. Filming time per video dropped from 90 minutes to 25. Retention climbed from 28% to 52%. Six months in: 8,000 subscribers and a process he actually enjoys.'
  },
  {
    chapter: 12,
    why: 'Your audience does not care about your editing the way you think they do. Spending eight hours on a ten-minute video, color grading like Sundance, building custom motion graphics, that is procrastination disguised as productivity. This worksheet builds the editing template that makes every future video faster: define your essentials (jump cuts, B-roll, on-screen text, pattern interrupts, audio cleanup), set a two-hour cap, save a project template you reuse forever. A good video published beats a perfect video in progress. Your job is to serve your audience, not to win editing awards.',
    aaronNote: 'Your editing should be invisible. When someone comments "Great editing!" on a business video, that is a warning sign. It means the editing was noticeable enough to pull attention away from the message. Every edit must earn its place. The pursuit of perfection is what makes most people sound robotic in the first place.',
    caseStudyBlurb: 'Marcus, the financial advisor, also had a videographer background and was spending 12 to 15 hours editing each video like a broadcast production. He published once a month while a competitor with basic jump cuts published three times a week and crushed him. We capped his edits at two hours. Six months later he was publishing twice a week, total monthly editing time dropped from 15 plus hours to 8, and subscribers grew from 400 to 4,200.'
  },
  {
    chapter: 13,
    why: 'Publishing is not the end of the process. It is the beginning of a launch. The 48 hours after you hit publish are when YouTube decides whether to push your video to a wider audience or let it fade. Creators throw away great content with sloppy metadata, blank descriptions, and zero promotion. This worksheet builds your pre-publish and post-publish checklists once, then reuses them on every video forever. Adds 15 to 25 minutes per upload. Compounds across hundreds of videos into millions of additional views over time.',
    aaronNote: 'YouTube is constantly testing your content. When a new video goes live, the algorithm shows it to a small sample of viewers and watches carefully. The discipline of consistent execution is what separates channels that grow predictably from channels that simply hope for the best.',
    caseStudyBlurb: 'Rachel, a business coach, was getting wildly inconsistent results because her publishing process was chaos: sometimes detailed descriptions, sometimes blank, no consistent thumbnails, no comment responses in the critical first 24 hours. We installed a simple checklist. Over 90 days her average views per video climbed from 650 to 1,800, comments jumped from 4 to 18, subscriber growth went up 2.3x, and lead magnet downloads went from 8 per month to 34.'
  },
  {
    chapter: 14,
    why: 'Feast or famine kills more YouTube channels than bad content ever will. Three videos in a week, then six weeks of silence, then a guilt-fueled return that fizzles out by month two. This worksheet replaces willpower with a system: pick a frequency you can hold during your busiest season, design a monthly batch schedule (planning day, filming day, spread editing across weeks), build your safety net before you need it (two-week buffer, emergency stash, reduced-frequency plan), and lock in your first four weeks of topics. Consistency is the highest-ROI behavior on YouTube.',
    aaronNote: 'YouTube rewards consistency more than quality. I know that stings. We all want to believe our brilliant one-off video will change everything. The algorithm is designed to promote creators who show up reliably, because those are the creators who keep viewers coming back to the platform.',
    caseStudyBlurb: 'Mike was a Colorado agent stuck in feast-or-famine for 18 months: 31 total videos, barely any movement. We set him to one video per week on Mondays, monthly batch filming on the first Sunday (four videos in three hours, same outfit), plus a buffer and emergency stash. Twelve months later: 52 videos, zero missed weeks, subscribers up from 340 to 4,100, and 4 to 5 leads per month.'
  },
  {
    chapter: 15,
    why: 'YouTube Studio gives you hundreds of data points and most of them do not matter. Creators either ignore analytics entirely or check ten times a day and spiral over every fluctuation. Both are wrong. This worksheet establishes your baseline (CTR, AVD, average views, sub conversion), identifies your single biggest bottleneck by comparing your best and worst videos, and locks in a 15-minute weekly review on your calendar. Data-driven creators outperform gut-feeling creators every single time. Start with diagnosis, end with one focused fix.',
    aaronNote: 'Train yourself to ask, "Did this video do its job?" instead of, "Did this video go viral?" Most metrics YouTube shows you do not matter. They are interesting. They are fun to look at. But they do not drive decisions that improve your channel.',
    caseStudyBlurb: 'Kevin, a financial advisor, was stuck at 1,200 subscribers and obsessing over views. His CTR was a great 6.2% but his AVD was a brutal 32%. The problem was a long, formal intro every video. We rewrote his openings to lead with value ("Claiming Social Security at the wrong time could cost you over $100,000"). Over 90 days AVD climbed from 32% to 51%, average views jumped from 500 to 2,100, and client inquiries went from 1 to 2 per month to 8 to 10.'
  },
  {
    chapter: 16,
    why: 'Shorts are a tool, not a strategy. Used right, they amplify your channel. Used wrong, they attract the wrong audience and dilute everything you have built. This worksheet sets the boundaries before you get intoxicated by view counts: define the role Shorts play (trailer, topic test, reach extender), set your ratio (1 Short for every 2 to 3 long-form), commit to repurposed-only (never original creation), and identify five Short-worthy moments from your last five videos. Track Shorts-to-long-form conversion. If they are not feeding the main channel, scale back.',
    aaronNote: 'Shorts should feel like movie trailers for your real content. They are not the main event. They are the teaser that gets people into the theater. A Short with 50,000 views that sends 5,000 people to your full video is worth more than a viral Short with a million views that sends nobody.',
    caseStudyBlurb: 'Lisa, a real estate agent with 8,000 subscribers, wanted Shorts without the typical trap. We capped her at two repurposed Shorts per week pulled from existing long-form, every one bridging back to the full video. Over six months: 850,000 Shorts views, 3,200 new subscribers, long-form views up 22%, total subs from 8,000 to 14,500, and monthly leads from 5 to 8 up to 12 to 15. About 80 minutes of extra work per month.'
  },
  {
    chapter: 17,
    why: 'YouTube generates attention. What you do with that attention determines whether your channel becomes a business asset or an expensive hobby. Most creators skip building a lead system entirely, then wonder why their 5,000 subscribers produce zero clients. This worksheet builds the complete pipeline in 90 minutes: design your lead magnet, build a capture page, write your standard verbal CTA and pinned comment, outline your five-email welcome sequence. Hard deadline of seven days. Every video published without a lead system is wasted opportunity that disappears into the void.',
    aaronNote: 'YouTube by itself does not generate leads. It generates attention. Without a system to capture leads, even the best content is just entertainment. You might build an audience, but you will not build a business. A list of uncontacted leads is barely better than no list at all.',
    caseStudyBlurb: 'Sandra, a divorce attorney with 3,200 subscribers, had gotten exactly four leads in eight months. No lead magnet, no capture page, just a phone number in her descriptions. We built "The Divorce Preparation Checklist" with a Leadpages capture page and a five-email sequence. Over 90 days: 340 downloads, 62 consultation requests, 11 new clients, and $93,500 in revenue directly attributed to YouTube.'
  },
  {
    chapter: 18,
    why: 'YouTube leads are different. They have watched you for weeks or months before reaching out, which means trust is already built. But most creators blow it by treating these calls like cold pitches: skipping the YouTube connection, giving away the solution for free, vague presentations, and a weak close. This worksheet rebuilds your consultation framework: scripted opening that activates the existing relationship, five discovery questions, a bridge statement, a specific presentation, a direct close, and rehearsed responses to the three most common objections. Done right, you should close at 2 to 3x your cold rate.',
    aaronNote: 'YouTube leads are not strangers. They already trust you. Your job is not to prove yourself. It is to understand their situation and show them the path forward. Stop treating consultations like auditions and start treating them like conversations with people who already wanted to work with you.',
    caseStudyBlurb: 'Robert, a business consultant, was getting 12 to 15 consultation requests a month from YouTube but closing only 20%. He skipped the YouTube connection on calls, gave away the solution for free, presented vaguely, and feared the close. We rebuilt all four. After 60 days his close rate jumped from 20% to 48%, brain-picker calls dropped from 40% to 10%, and monthly revenue roughly doubled from the same lead volume.'
  },
  {
    chapter: 19,
    why: 'There is a ceiling every solo creator hits. You can only film, edit, design, write, post, and respond to so much before you cap out. This worksheet gets you ready to scale strategically (not too early, not all at once): an honest readiness assessment, time-tracking to identify your real first hire (usually an editor), starting your style guide, and designing a paid test project. Hiring without systems creates chaos. The creators who scale successfully document first, then hire. The ones who fail try to hand off everything to someone who cannot read their mind.',
    aaronNote: 'The first time creators try to hire, they are trying to save time. The second time, they are trying to build a system. The difference is everything. Hiring is not a magic solution. You will spend time training, reviewing work, giving feedback, and communicating.',
    caseStudyBlurb: 'Amanda, a business coach with 12,000 subscribers, was burning 15 to 20 hours a week on YouTube production. Her first Fiverr editor was a disaster because she had no documentation. We rebuilt the process: style guide, Loom walkthroughs, paid test projects, then a 30-day trial. Six months in, her YouTube time dropped to 4 to 5 hours, publishing doubled, subscribers grew from 12,000 to 24,000, and coaching revenue roughly doubled.'
  },
  {
    chapter: 20,
    why: 'Nobody talks about the crying. The night you stare at a video that took eight hours and watch it sit at 43 views. The comment from a stranger that echoes louder than a hundred compliments. The technical and strategic stuff is learnable. The psychological game is where most channels actually die. This worksheet builds your resilience system: an Evidence Journal of every win, strict analytics boundaries (one day a week, app deleted from your phone), a real creator support network, and a 100-video commitment you sign before you give yourself permission to evaluate.',
    aaronNote: 'The creators who reach 10,000 subscribers are not necessarily more talented or more strategic than those who quit at 200. They are tougher. They have learned to manage their own psychology. A video that gets 200 views is not a statement about your worth. It is data about one piece of content under a specific set of conditions.',
    caseStudyBlurb: 'Leah, a real estate agent in Washington, was four months in with 280 subscribers, six finished videos hoarded on her hard drive because they "were not good enough", and a brutal comparison spiral with another agent in her market. We installed an Evidence Journal, deleted YouTube Studio from her phone, and reframed the comparison. Six months later: 2,800 subscribers, 8 to 12 leads a month, 14 transactions, and over $180,000 in commissions.'
  },
  {
    chapter: 21,
    why: 'A channel with 30,000 passive followers loses to a channel with 3,000 engaged community members every single time. The algorithm rewards engagement signals, social proof closes deals, and your most loyal viewers become an unpaid marketing team. This worksheet turns your channel from a broadcast into a gathering place: define your community identity, set engagement windows, build a question bank for end-of-video CTAs, plan two weeks of Community tab posts, and baseline your metrics. An audience watches your content. A community creates momentum around it.',
    aaronNote: 'You cannot buy a community. You cannot fake it. But you can absolutely build it. Community building compounds like content does. The first few weeks feel like nothing is happening. Keep going. Those handfuls of engaged viewers become the reason your channel keeps growing, even on the weeks you do not feel like showing up.',
    caseStudyBlurb: 'Elena, a financial planner stuck at 4,500 subscribers, was broadcasting into a void: handful of generic comments, no Community tab posts, no follow-ups. We installed five changes including specific end-of-video questions, three Community posts a week, and naming her tribe "The Financial Freedom Crew". Six months later: comments per video jumped from 8 to 12 up to 45 to 70, subscribers from 4,500 to 11,200, and client inquiries tripled.'
  },
  {
    chapter: 22,
    why: 'Every video you publish without repurposing is a half-finished job. You did the hard part (the filming, the editing, the expertise). One YouTube video can become twelve to fifteen pieces of content across LinkedIn, Reels, email, blog, and podcast for about 20% more effort and roughly 300% more reach. This worksheet locks in your two distribution platforms (not seven, two), defines what you create from each video, maps the workflow, and forces you to actually repurpose your last video right now. Not tomorrow. Now. The first one is the hardest. After that it becomes muscle memory.',
    aaronNote: 'YouTube is the hub. Everything else is distribution. You do not need seven content strategies. You need one content strategy with a distribution plan. Each platform is not competing with YouTube, they are feeding it. Repurposing is about cumulative visibility, not individual home runs.',
    caseStudyBlurb: 'David, a business attorney with 6,000 subscribers, only existed on YouTube while his startup-founder clients lived on LinkedIn and in podcast apps. We built a repurposing system around his existing videos: vertical clips, podcast audio, LinkedIn articles, and email. Six months later: LinkedIn followers from 800 to 4,200, podcast hit 1,500 monthly downloads from zero, email list nearly quintupled, and monthly leads went from 3 to 4 up to 12 to 15.'
  },
  {
    chapter: 23,
    why: 'Views do not pay the bills. Subscribers do not pay the bills. If you cannot tell me how many leads, consultations, clients, and dollars YouTube generated last quarter, you are operating on vibes instead of data. This worksheet installs your tracking system in one sitting: UTM-tagged links, a "How did you find me?" intake field, a standard consultation question, a five-column client source log in Google Sheets, and your first ROI calculation. Most creators never do this. That is exactly why they keep guessing about content, time, and strategy.',
    aaronNote: 'Knowing how many clients walked through your door because of YouTube, and what those clients were worth, is the only number that matters. Once tracking is in place, the fog lifts. You stop guessing and start making decisions with actual data.',
    caseStudyBlurb: 'Marcus, a business consultant with 7,800 subscribers, was operating on vibes after 14 months. We installed UTM links, intake-form tracking, a standard discovery question, and a Google Sheet log. After 90 days: 127 leads, 11 clients, $88,000 in revenue, and a 114% ROI. The data exposed his real bottleneck (a 0.16% view-to-lead rate). One quarter of focused fixes later: leads jumped to 287, clients to 19, and revenue hit $152,000.'
  },
  {
    chapter: 24,
    why: 'The next 90 days pass whether you build your channel or not. Most readers will close the book and do nothing. The few who execute will not be smarter or more talented. They will just decide to start and refuse to stop. This worksheet is the most important exercise in the book because it is not information. It is a decision. You write down your why, your schedule, this weeks specific actions, your accountability partner, and you sign your name. Then you put it somewhere you will see it every day. You have everything you need. The only variable left is you.',
    aaronNote: 'You will have a week somewhere in this 90 days where you want to quit. Every single creator I have coached has had that moment. The ones who made it through did not have more motivation or thicker skin. They just had a plan that told them what to do next, so they did the next thing instead of spiraling.',
    caseStudyBlurb: 'Scott had been "on YouTube" for twelve years and accumulated 200 subscribers. No strategy, no system, no results. He committed to 90 days of following the roadmap exactly: foundation, launch, optimize, accelerate. The result: 200 to 2,000 subscribers, 14 videos published, 156 lead magnet downloads, 23 consultations, 4 clients, $87,000 in commissions. By year one, YouTube had generated over $300,000 in revenue from the channel he had ignored for over a decade.'
  }
]
